export const RESOURCE_CATEGORIES = Object.freeze([
  'ui-css',
  'components',
  'icons',
  'fonts',
  'animation',
  'images',
  'cdn',
])

const COMPAT = ['react', 'vite', 'jsx', 'css']

export const DESIGN_RESOURCES = Object.freeze([
  {
    id: 'native-css',
    name: 'Native CSS',
    category: 'ui-css',
    cdn: null,
    version: 'platform',
    documentation: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
    usage: 'Prefer custom CSS in src/index.css using design tokens. Do not load a CSS framework unless the user asked for one.',
    compatibleWith: COMPAT,
    license: 'n/a',
    weight: 'none',
    a11y: 'Full control of focus, contrast, and reduced-motion.',
    mobile: true,
    tags: ['native', 'custom', 'tokens'],
  },
  {
    id: 'pico',
    name: 'Pico CSS',
    category: 'ui-css',
    cdn: 'https://cdn.jsdelivr.net/npm/@picocss/pico@2.0.6/css/pico.min.css',
    version: '2.0.6',
    documentation: 'https://picocss.com',
    usage: 'Classless semantic defaults. Only if the user asked for Pico or a tiny classless baseline. Override with brand tokens; do not ship a Pico-looking page.',
    compatibleWith: COMPAT,
    license: 'MIT',
    weight: 'small',
    a11y: 'Semantic HTML required; restyle focus rings.',
    mobile: true,
    tags: ['classless', 'minimal'],
  },
  {
    id: 'bulma',
    name: 'Bulma',
    category: 'ui-css',
    cdn: 'https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css',
    version: '1.0.2',
    documentation: 'https://bulma.io',
    usage: 'Use individual layout ideas, not the whole Bulma look. Do not add unless requested.',
    compatibleWith: COMPAT,
    license: 'MIT',
    weight: 'medium',
    a11y: 'Restyle components; keep semantic markup.',
    mobile: true,
    tags: ['flexbox', 'columns'],
  },
  {
    id: 'uikit',
    name: 'UIkit',
    category: 'ui-css',
    cdn: 'https://cdn.jsdelivr.net/npm/uikit@3.21.13/dist/css/uikit.min.css',
    js: 'https://cdn.jsdelivr.net/npm/uikit@3.21.13/dist/js/uikit.min.js',
    version: '3.21.13',
    documentation: 'https://getuikit.com',
    usage: 'Reference components only. Avoid loading unless the user named UIkit.',
    compatibleWith: COMPAT,
    license: 'MIT',
    weight: 'large',
    a11y: 'Verify keyboard behavior if JS widgets are used.',
    mobile: true,
    tags: ['components'],
  },
  {
    id: 'bootstrap',
    name: 'Bootstrap',
    category: 'ui-css',
    cdn: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css',
    js: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js',
    version: '5.3.3',
    documentation: 'https://getbootstrap.com',
    usage: 'Do not produce a Bootstrap template. Only load if the user explicitly asked for Bootstrap.',
    compatibleWith: COMPAT,
    license: 'MIT',
    weight: 'large',
    a11y: 'Keep native semantics; do not rely on data-bs widgets for essential nav.',
    mobile: true,
    tags: ['grid', 'components', 'corporate'],
  },
  {
    id: 'tailwind-cdn',
    name: 'Tailwind CDN',
    category: 'ui-css',
    cdn: 'https://cdn.jsdelivr.net/npm/tailwindcss@3.4.17/lib/index.min.js',
    playCdn: 'https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4.0.9/dist/index.global.js',
    version: '3.4.17',
    documentation: 'https://tailwindcss.com',
    usage: 'Play CDN is for prototypes only and is heavy. Do not add unless the user asked for Tailwind. Prefer handwritten CSS.',
    compatibleWith: COMPAT,
    license: 'MIT',
    weight: 'large',
    a11y: 'You still own contrast and focus styles.',
    mobile: true,
    tags: ['utility'],
  },
  {
    id: 'lucide',
    name: 'Lucide',
    category: 'icons',
    cdn: 'https://cdn.jsdelivr.net/npm/lucide@0.468.0/dist/umd/lucide.min.js',
    version: '0.468.0',
    documentation: 'https://lucide.dev',
    usage: 'Preferred icon system. In React, inline SVG with 1.5 stroke and 24 viewBox. Optional: data-lucide plus lucide.createIcons() after paint. Do not mix with Font Awesome.',
    compatibleWith: COMPAT,
    license: 'ISC',
    weight: 'small',
    a11y: 'Decorative icons aria-hidden; interactive icons need names.',
    mobile: true,
    tags: ['svg', 'stroke', 'lightweight'],
    injectCdn: false,
    icons: ['menu', 'x', 'arrow-right', 'instagram', 'phone', 'mail', 'shopping-bag', 'heart'],
  },
  {
    id: 'font-awesome',
    name: 'Font Awesome',
    category: 'icons',
    cdn: 'https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.5.2/css/all.min.css',
    version: '6.5.2',
    documentation: 'https://fontawesome.com',
    usage: 'Use only if the user asked for Font Awesome or the site already uses it. Do not mix with Lucide.',
    compatibleWith: COMPAT,
    license: 'Font Awesome Free (CC-BY-4.0 icons, SIL OFL, MIT code)',
    weight: 'medium',
    a11y: 'Use aria-hidden on purely decorative <i>.',
    mobile: true,
    tags: ['webfont', 'icons'],
  },
  {
    id: 'bootstrap-icons',
    name: 'Bootstrap Icons',
    category: 'icons',
    cdn: 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css',
    version: '1.11.3',
    documentation: 'https://icons.getbootstrap.com',
    usage: 'Only with an existing Bootstrap stack or explicit request.',
    compatibleWith: COMPAT,
    license: 'MIT',
    weight: 'medium',
    a11y: 'Prefer SVG; hide decorative webfont glyphs.',
    mobile: true,
    tags: ['webfont'],
  },
  {
    id: 'material-symbols',
    name: 'Material Symbols',
    category: 'icons',
    cdn: 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0',
    version: 'outlined-24-400',
    documentation: 'https://fonts.google.com/icons',
    usage: 'Only for product/tech UIs that already speak Material. Not for editorial fashion.',
    compatibleWith: COMPAT,
    license: 'Apache 2.0',
    weight: 'medium',
    a11y: 'ligature icons need accessible names.',
    mobile: true,
    tags: ['google', 'material'],
  },
  {
    id: 'font-editorial-fashion',
    name: 'Playfair Display + Outfit',
    category: 'fonts',
    cdn: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700&family=Playfair+Display:wght@500;600;700&display=swap',
    version: 'css2',
    documentation: 'https://fonts.google.com',
    usage: 'Fashion / editorial: serif display headings, modern sans body. Map to --heading-font and --body-font.',
    compatibleWith: COMPAT,
    license: 'OFL (Google Fonts)',
    weight: 'small',
    a11y: 'Keep body size ≥16px; check contrast on gold/cream.',
    mobile: true,
    tags: ['fashion', 'editorial', 'luxury', 'serif', 'clothing'],
    heading: 'Playfair Display, Georgia, serif',
    body: 'Outfit, Helvetica, sans-serif',
  },
  {
    id: 'font-luxury',
    name: 'Cormorant Garamond + Jost',
    category: 'fonts',
    cdn: 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=Jost:wght@400;500;600&display=swap',
    version: 'css2',
    documentation: 'https://fonts.google.com',
    usage: 'Luxury / quiet premium. Large whitespace, restrained sans for UI.',
    compatibleWith: COMPAT,
    license: 'OFL (Google Fonts)',
    weight: 'small',
    a11y: 'Thin serif weights need larger type.',
    mobile: true,
    tags: ['luxury', 'elegant', 'premium'],
    heading: 'Cormorant Garamond, Georgia, serif',
    body: 'Jost, Helvetica, sans-serif',
  },
  {
    id: 'font-tech',
    name: 'Space Grotesk + IBM Plex Sans',
    category: 'fonts',
    cdn: 'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&family=Space+Grotesk:wght@500;600;700&display=swap',
    version: 'css2',
    documentation: 'https://fonts.google.com',
    usage: 'Technology / product: geometric sans headings.',
    compatibleWith: COMPAT,
    license: 'OFL (Google Fonts)',
    weight: 'small',
    a11y: 'Good UI readability.',
    mobile: true,
    tags: ['technology', 'modern', 'geometric', 'product'],
    heading: 'Space Grotesk, Helvetica, sans-serif',
    body: 'IBM Plex Sans, Helvetica, sans-serif',
  },
  {
    id: 'font-modern',
    name: 'Syne + Manrope',
    category: 'fonts',
    cdn: 'https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&family=Syne:wght@600;700;800&display=swap',
    version: 'css2',
    documentation: 'https://fonts.google.com',
    usage: 'Contemporary brand sites, asymmetric layouts.',
    compatibleWith: COMPAT,
    license: 'OFL (Google Fonts)',
    weight: 'small',
    a11y: 'Syne is display-only — never for long body copy.',
    mobile: true,
    tags: ['modern', 'asymmetric', 'ultra-modern'],
    heading: 'Syne, Futura, sans-serif',
    body: 'Manrope, Helvetica, sans-serif',
  },
  {
    id: 'font-inter',
    name: 'Inter',
    category: 'fonts',
    cdn: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
    version: 'css2',
    documentation: 'https://fonts.google.com/specimen/Inter',
    usage: 'Neutral UI. Avoid for luxury fashion heroes.',
    compatibleWith: COMPAT,
    license: 'OFL',
    weight: 'small',
    a11y: 'Excellent body text.',
    mobile: true,
    tags: ['neutral', 'ui', 'saas'],
    heading: 'Inter, Helvetica, sans-serif',
    body: 'Inter, Helvetica, sans-serif',
  },
  {
    id: 'font-fontshare-satoshi',
    name: 'Satoshi (Fontshare)',
    category: 'fonts',
    cdn: 'https://api.fontshare.com/v2/css?f[]=satoshi@400,500,700&display=swap',
    version: 'fontshare-v2',
    documentation: 'https://www.fontshare.com/fonts/satoshi',
    usage: 'Optional geometric sans from Fontshare. Only if the user asked for Fontshare or Satoshi.',
    compatibleWith: COMPAT,
    license: 'Fontshare (check font page)',
    weight: 'small',
    a11y: 'Good UI readability; keep body ≥16px.',
    mobile: true,
    tags: ['fontshare', 'geometric', 'satoshi', 'technology'],
    heading: 'Satoshi, Helvetica, sans-serif',
    body: 'Satoshi, Helvetica, sans-serif',
  },
  {
    id: 'css-animation',
    name: 'Native CSS animation',
    category: 'animation',
    cdn: null,
    version: 'platform',
    documentation: 'https://developer.mozilla.org/en-US/docs/Web/CSS/animation',
    usage: 'Default. Use @media (prefers-reduced-motion: reduce). Fade, underline, transform only.',
    compatibleWith: COMPAT,
    license: 'n/a',
    weight: 'none',
    a11y: 'Honor reduced motion.',
    mobile: true,
    tags: ['css', 'simple'],
  },
  {
    id: 'aos',
    name: 'AOS',
    category: 'animation',
    cdn: 'https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css',
    js: 'https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js',
    version: '2.3.4',
    documentation: 'https://michalsnik.github.io/aos/',
    usage: 'Scroll reveals only when the request needs them. Init with disable: prefers-reduced-motion. Site must work without it.',
    compatibleWith: COMPAT,
    license: 'MIT',
    weight: 'small',
    a11y: 'Disable when reduced-motion is set.',
    mobile: true,
    tags: ['scroll', 'reveal'],
  },
  {
    id: 'gsap',
    name: 'GSAP',
    category: 'animation',
    cdn: 'https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js',
    version: '3.12.5',
    documentation: 'https://gsap.com',
    usage: 'Only for timeline / cinematic motion. Never for a contact form. Keep content visible if the script fails.',
    compatibleWith: COMPAT,
    license: 'Standard GSAP license (CDN standard)',
    weight: 'medium',
    a11y: 'Do not trap scroll; respect reduced motion.',
    mobile: true,
    tags: ['timeline', 'cinematic', 'immersive'],
  },
  {
    id: 'motion-one',
    name: 'Motion One',
    category: 'animation',
    cdn: 'https://cdn.jsdelivr.net/npm/motion@10.18.0/dist/motion.min.js',
    version: '10.18.0',
    documentation: 'https://motion.dev',
    usage: 'Smaller WAAPI helper. Prefer CSS unless interaction is complex.',
    compatibleWith: COMPAT,
    license: 'MIT',
    weight: 'small',
    a11y: 'WAAPI honors reduced motion if you check matchMedia.',
    mobile: true,
    tags: ['waapi', 'transitions'],
  },
  {
    id: 'lenis',
    name: 'Lenis',
    category: 'animation',
    cdn: 'https://cdn.jsdelivr.net/npm/lenis@1.1.18/dist/lenis.min.js',
    version: '1.1.18',
    documentation: 'https://github.com/darkroomengineering/lenis',
    usage: 'Smooth scrolling only when requested. Never required for navigation.',
    compatibleWith: COMPAT,
    license: 'MIT',
    weight: 'small',
    a11y: 'Do not break native keyboard scrolling.',
    mobile: true,
    tags: ['smooth-scroll'],
  },
  {
    id: 'getvia-images',
    name: 'GetVia business images',
    category: 'images',
    cdn: null,
    version: 'workspace',
    documentation: null,
    usage: 'Always prefer business.json logo, gallery, service, and product images before any stock photo.',
    compatibleWith: COMPAT,
    license: 'business-owned',
    weight: 'none',
    a11y: 'Meaningful alt from product/service names.',
    mobile: true,
    tags: ['first-party', 'cloudinary'],
  },
  {
    id: 'unsplash',
    name: 'Unsplash',
    category: 'images',
    cdn: 'https://images.unsplash.com',
    version: 'images',
    documentation: 'https://unsplash.com/license',
    usage: 'Only real Unsplash image URLs. Never invent photo ids. Add alt text and loading="lazy". Prefer GetVia images.',
    compatibleWith: COMPAT,
    license: 'Unsplash License',
    weight: 'network',
    a11y: 'Required alt; lazy load below the fold.',
    mobile: true,
    tags: ['stock', 'photography'],
  },
  {
    id: 'pexels',
    name: 'Pexels',
    category: 'images',
    cdn: 'https://images.pexels.com',
    version: 'images',
    documentation: 'https://www.pexels.com/license/',
    usage: 'Only real Pexels URLs. Never invent paths.',
    compatibleWith: COMPAT,
    license: 'Pexels License',
    weight: 'network',
    a11y: 'Required alt.',
    mobile: true,
    tags: ['stock'],
  },
  {
    id: 'pixabay',
    name: 'Pixabay',
    category: 'images',
    cdn: 'https://cdn.pixabay.com',
    version: 'images',
    documentation: 'https://pixabay.com/service/license-summary/',
    usage: 'Only real Pixabay CDN URLs.',
    compatibleWith: COMPAT,
    license: 'Pixabay Content License',
    weight: 'network',
    a11y: 'Required alt.',
    mobile: true,
    tags: ['stock'],
  },
])

export const COMPONENT_REFERENCES = Object.freeze([
  {
    id: 'editorial-nav',
    name: 'Editorial navigation',
    category: 'components',
    kind: 'navigation',
    tags: ['nav', 'fashion', 'luxury', 'editorial'],
    structure: ['wordmark', 'text links', 'bag/account icon', 'mobile details/summary menu'],
    cssIdeas: ['hairline bottom border', 'wide letter-spacing labels', 'no hamburger animation library'],
    js: 'none — use <details> for mobile',
    adapt: 'Brand name from business.name. Do not use Bootstrap navbar.',
  },
  {
    id: 'immersive-hero',
    name: 'Immersive fashion hero',
    category: 'components',
    kind: 'hero',
    tags: ['hero', 'fashion', 'premium', 'editorial', 'clothing'],
    structure: ['full-viewport media', 'eyebrow', 'display title', 'lede', 'primary CTA', 'optional secondary text link'],
    cssIdeas: ['min-height 100svh', 'split or overlay type', 'serif display'],
    js: 'none',
    adapt: 'Use business.hero and first gallery/product image. Keep WhatsApp/booking CTAs that already exist.',
  },
  {
    id: 'product-grid',
    name: 'Asymmetric product grid',
    category: 'components',
    kind: 'product-grids',
    tags: ['products', 'cards', 'fashion', 'lookbook'],
    structure: ['section kicker', 'mixed-size tiles', 'name', 'price', 'shop action'],
    cssIdeas: ['not equal cards', 'object-fit cover', 'hover crop only if reduced-motion allows'],
    js: 'none',
    adapt: 'business.products / catalogue. Never dummy Unsplash if GetVia images exist.',
  },
  {
    id: 'lookbook',
    name: 'Lookbook strip',
    category: 'components',
    kind: 'galleries',
    tags: ['gallery', 'fashion', 'horizontal'],
    structure: ['horizontal snap row or editorial mosaic', 'captions optional'],
    cssIdeas: ['scroll-snap', 'no slider library unless requested'],
    js: 'native scroll-snap',
    adapt: 'business.gallery.',
  },
  {
    id: 'testimonial-deck',
    name: 'Testimonial deck',
    category: 'components',
    kind: 'testimonials',
    tags: ['reviews', 'testimonials'],
    structure: ['quote', 'name', 'optional rating'],
    cssIdeas: ['large quotation typography', 'not a carousel by default'],
    js: 'none',
    adapt: 'business.reviews.',
  },
  {
    id: 'pricing-bands',
    name: 'Pricing bands',
    category: 'components',
    kind: 'pricing',
    tags: ['pricing', 'offers'],
    structure: ['plan/offer name', 'price', 'notes', 'CTA'],
    cssIdeas: ['simple columns', 'no comparison-table plugin'],
    js: 'none',
    adapt: 'business.pricing or offers.',
  },
  {
    id: 'fashion-cta',
    name: 'Fashion CTA band',
    category: 'components',
    kind: 'cta',
    tags: ['cta', 'fashion', 'contact'],
    structure: ['short line', 'one primary action'],
    cssIdeas: ['full-bleed contrast band', 'single button'],
    js: 'none',
    adapt: 'Keep existing booking/WhatsApp destinations.',
  },
  {
    id: 'colophon-footer',
    name: 'Colophon footer',
    category: 'components',
    kind: 'footers',
    tags: ['footer', 'editorial'],
    structure: ['brand', 'links', 'contact', 'copyright'],
    cssIdeas: ['three columns collapsing to stack', 'small caps labels'],
    js: 'none',
    adapt: 'Keep existing WhatsApp, phone, and email.',
  },
  {
    id: 'faq-accordion',
    name: 'Native accordion',
    category: 'components',
    kind: 'accordions',
    tags: ['faq', 'accordion'],
    structure: ['details/summary pairs'],
    cssIdeas: ['marker-free summary', 'focus-visible'],
    js: 'none — native <details>',
    adapt: 'business.faq.',
  },
  {
    id: 'contact-form',
    name: 'Simple contact form',
    category: 'components',
    kind: 'forms',
    tags: ['forms', 'contact'],
    structure: ['name', 'contact', 'message', 'submit'],
    cssIdeas: ['labels always visible', 'no form library'],
    js: 'none required',
    adapt: 'mailto or existing contact actions. No GSAP.',
  },
  {
    id: 'card-collection',
    name: 'Service/product cards',
    category: 'components',
    kind: 'cards',
    tags: ['cards', 'services'],
    structure: ['image optional', 'title', 'body', 'price optional'],
    cssIdeas: ['token radius/shadow', 'not Bootstrap .card'],
    js: 'none',
    adapt: 'business.services.',
  },
  {
    id: 'tabs-native',
    name: 'Native tabs',
    category: 'components',
    kind: 'tabs',
    tags: ['tabs', 'menus'],
    structure: ['tablist of buttons', 'panels'],
    cssIdeas: ['ARIA tabs only if JS is added; otherwise stacked sections'],
    js: 'optional small keyboard handler — no UIKit',
    adapt: 'Prefer stacked sections on a one-pager.',
  },
  {
    id: 'modal-native',
    name: 'Native modal',
    category: 'components',
    kind: 'modals',
    tags: ['modal', 'dialog'],
    structure: ['button opener', 'dialog', 'close', 'focus return'],
    cssIdeas: ['native <dialog> or hidden class', 'focus-visible on close'],
    js: 'optional showModal() — no library',
    adapt: 'Never block essential booking/WhatsApp behind a modal-only path.',
  },
  {
    id: 'slider-snap',
    name: 'Scroll-snap slider',
    category: 'components',
    kind: 'sliders',
    tags: ['slider', 'carousel', 'gallery'],
    structure: ['horizontal track', 'snap slides', 'optional dots'],
    cssIdeas: ['scroll-snap-type x mandatory', 'no Swiper unless requested'],
    js: 'none required',
    adapt: 'Use for lookbooks only when a grid would overflow. Honor reduced motion.',
  },
  {
    id: 'overflow-menu',
    name: 'Details menu',
    category: 'components',
    kind: 'menus',
    tags: ['menu', 'navigation', 'mobile'],
    structure: ['details/summary', 'links'],
    cssIdeas: ['full-width drawer on small screens'],
    js: 'none — native details',
    adapt: 'Keyboard accessible without an animation library.',
  },
])

export function getResourceById(id) {
  const key = String(id || '').trim().toLowerCase()
  return (
    DESIGN_RESOURCES.find((row) => row.id === key || row.name.toLowerCase() === key) ||
    COMPONENT_REFERENCES.find((row) => row.id === key || row.name.toLowerCase() === key) ||
    null
  )
}

export function listResources(category) {
  const cat = String(category || '').trim().toLowerCase()
  if (!cat || cat === 'cdn') return [...DESIGN_RESOURCES, ...COMPONENT_REFERENCES]
  if (cat === 'components' || cat === 'component') return [...COMPONENT_REFERENCES]
  const mapped = cat === 'ui' || cat === 'css' ? 'ui-css' : cat === 'font' ? 'fonts' : cat === 'icon' ? 'icons' : cat
  return DESIGN_RESOURCES.filter((row) => row.category === mapped)
}
