/**
 * Universal GetVia design library — industries map to direction pools (not one fixed look).
 */

export const INDUSTRY_IDS = Object.freeze([
  'salon_beauty',
  'fashion_retail',
  'restaurant_food',
  'hotel_hospitality',
  'clinic_health',
  'fitness_wellness',
  'technology_saas',
  'professional_services',
  'real_estate',
  'education',
  'automotive',
  'home_services',
  'creative_agency',
  'photography',
  'jewelry_luxury',
  'bakery_artisan',
  'travel_tourism',
  'nonprofit',
  'finance_legal',
  'industrial_trade',
  'pet_care',
  'events_wedding',
  'general_local',
])

const INDUSTRIES = Object.freeze({
  salon_beauty: {
    id: 'salon_beauty',
    label: 'Salon & Beauty',
    match: /salon|beauty|spa|bridal|makeup|hair|nail|barber|skincare/i,
    directions: ['soft-luxury', 'minimal-luxury', 'editorial', 'wellness-zen', 'warm-retail', 'magazine'],
    heroes: ['hero-soft-split', 'hero-portrait-editorial', 'hero-centered-void', 'hero-full-bleed'],
    services: ['services-soft-cards', 'services-list-luxury', 'services-editorial'],
    gallery: ['gallery-masonry', 'gallery-editorial', 'gallery-featured'],
    principles: ['hierarchy', 'whitespace', 'warmth', 'trust', 'imagery_first'],
    ctas: ['Book', 'WhatsApp', 'Call'],
  },
  fashion_retail: {
    id: 'fashion_retail',
    label: 'Fashion & Retail',
    match: /fashion|clothing|apparel|boutique|lookbook|retail|store|shop|gossip/i,
    directions: ['editorial', 'magazine', 'image-first', 'neo-minimal', 'brutalist', 'asymmetric'],
    heroes: ['hero-editorial', 'hero-typography-first', 'hero-full-bleed', 'hero-asymmetric', 'hero-lookbook'],
    services: ['services-lookbook-grid', 'services-editorial', 'services-minimal-rows'],
    gallery: ['gallery-editorial', 'gallery-masonry', 'gallery-runway'],
    principles: ['originality', 'typography_as_hero', 'visual_variety', 'negative_space'],
    ctas: ['Shop', 'WhatsApp', 'Visit'],
  },
  restaurant_food: {
    id: 'restaurant_food',
    label: 'Restaurant & Food',
    match: /restaurant|cafe|café|culinary|food|dining|kitchen|menu|bar\b/i,
    directions: ['image-first', 'editorial', 'organic', 'warm-retail', 'immersive', 'coastal'],
    heroes: ['hero-full-bleed', 'hero-split-menu', 'hero-centered-void', 'hero-immersive-stage'],
    services: ['services-menu-cards', 'services-list', 'services-featured-plates'],
    gallery: ['gallery-food-grid', 'gallery-masonry', 'gallery-full-bleed-strip'],
    principles: ['appetite_imagery', 'scannable_menu', 'local_trust', 'mobile_first'],
    ctas: ['Reserve', 'Call', 'WhatsApp', 'Directions'],
  },
  hotel_hospitality: {
    id: 'hotel_hospitality',
    label: 'Hotel & Hospitality',
    match: /hotel|resort|hospitality|villa|lodge|stay|guest\s*house/i,
    directions: ['immersive', 'minimal-luxury', 'coastal', 'organic', 'soft-luxury', 'editorial'],
    heroes: ['hero-immersive-stage', 'hero-full-bleed', 'hero-split', 'hero-centered-void'],
    services: ['services-amenity-grid', 'services-editorial', 'services-soft-cards'],
    gallery: ['gallery-immersive', 'gallery-masonry', 'gallery-featured'],
    principles: ['atmosphere', 'whitespace', 'trust', 'conversion_path'],
    ctas: ['Book', 'Check availability', 'WhatsApp'],
  },
  clinic_health: {
    id: 'clinic_health',
    label: 'Clinic & Health',
    match: /clinic|hospital|doctor|dental|medical|health|physio|ayurved/i,
    directions: ['clinical-clean', 'neo-minimal', 'corporate', 'soft-luxury', 'wellness-zen'],
    heroes: ['hero-clinical', 'hero-centered-void', 'hero-split', 'hero-trust-band'],
    services: ['services-list', 'services-icon-rail', 'services-grid-3'],
    gallery: ['gallery-simple-grid', 'gallery-featured'],
    principles: ['clarity', 'trust', 'accessibility', 'scannable_services'],
    ctas: ['Book', 'Call', 'Enquiry'],
  },
  fitness_wellness: {
    id: 'fitness_wellness',
    label: 'Fitness & Wellness',
    match: /fitness|gym|yoga|wellness|crossfit|pilates|trainer/i,
    directions: ['fitness-energy', 'neo-minimal', 'brutalist', 'wellness-zen', 'asymmetric'],
    heroes: ['hero-full-bleed', 'hero-asymmetric', 'hero-typography-first', 'hero-immersive-stage'],
    services: ['services-grid-3', 'services-numbered', 'services-bento'],
    gallery: ['gallery-masonry', 'gallery-full-bleed-strip'],
    principles: ['energy', 'hierarchy', 'conversion_path', 'mobile_first'],
    ctas: ['Join', 'Book', 'WhatsApp'],
  },
  technology_saas: {
    id: 'technology_saas',
    label: 'Technology & SaaS',
    match: /technolog|saas|software|startup|app|digital|it\b|cyber/i,
    directions: ['neo-minimal', 'tech-dark', 'saas-product', 'experimental-grid', 'corporate', 'asymmetric'],
    heroes: ['hero-product-ui', 'hero-one-line', 'hero-bento', 'hero-split'],
    services: ['services-feature-grid', 'services-bento', 'services-minimal-rows'],
    gallery: ['gallery-simple-grid', 'gallery-bento'],
    principles: ['clarity', 'consistency', 'performance', 'conversion_path'],
    ctas: ['Get started', 'Contact', 'Demo'],
  },
  professional_services: {
    id: 'professional_services',
    label: 'Professional Services',
    match: /consult|agency|accountant|architect|engineer|advisor|coach|lawyer|attorney|legal/i,
    directions: ['corporate', 'neo-minimal', 'minimal-luxury', 'editorial', 'finance-legal'],
    heroes: ['hero-centered-void', 'hero-split', 'hero-trust-band', 'hero-typography-first'],
    services: ['services-list', 'services-icon-rail', 'services-editorial'],
    gallery: ['gallery-simple-grid'],
    principles: ['trust', 'clarity', 'hierarchy', 'accessibility'],
    ctas: ['Enquire', 'Call', 'Book'],
  },
  real_estate: {
    id: 'real_estate',
    label: 'Real Estate',
    match: /real estate|property|homes|housing|realtor|broker/i,
    directions: ['real-estate-airy', 'image-first', 'minimal-luxury', 'editorial', 'corporate'],
    heroes: ['hero-full-bleed', 'hero-split', 'hero-card-overlay', 'hero-editorial'],
    services: ['services-property-cards', 'services-grid-3', 'services-list'],
    gallery: ['gallery-masonry', 'gallery-featured', 'gallery-editorial'],
    principles: ['imagery_first', 'scannable_listings', 'trust', 'mobile_first'],
    ctas: ['Enquire', 'Call', 'WhatsApp'],
  },
  education: {
    id: 'education',
    label: 'Education',
    match: /school|college|university|tutor|coaching|education|academy|institute/i,
    directions: ['education-bright', 'corporate', 'neo-minimal', 'soft-luxury', 'organic'],
    heroes: ['hero-split', 'hero-centered-void', 'hero-trust-band'],
    services: ['services-grid-3', 'services-list', 'services-numbered'],
    gallery: ['gallery-simple-grid', 'gallery-masonry'],
    principles: ['clarity', 'trust', 'accessibility', 'hierarchy'],
    ctas: ['Enquire', 'Apply', 'Call'],
  },
  automotive: {
    id: 'automotive',
    label: 'Automotive',
    match: /car|auto|garage|automotive|vehicle|detailing|wash/i,
    directions: ['asymmetric', 'industrial', 'tech-dark', 'brutalist', 'neo-minimal'],
    heroes: ['hero-full-bleed', 'hero-asymmetric', 'hero-industrial', 'hero-split'],
    services: ['services-grid-3', 'services-icon-rail', 'services-bento'],
    gallery: ['gallery-masonry', 'gallery-full-bleed-strip'],
    principles: ['bold_hierarchy', 'trust', 'conversion_path'],
    ctas: ['Book', 'Call', 'WhatsApp'],
  },
  home_services: {
    id: 'home_services',
    label: 'Home Services',
    match: /plumb|electric|hvac|cleaning|pest|repair|contractor|painter|carpenter/i,
    directions: ['corporate', 'neo-minimal', 'warm-retail', 'industrial', 'asymmetric'],
    heroes: ['hero-split', 'hero-trust-band', 'hero-centered-void'],
    services: ['services-icon-rail', 'services-grid-3', 'services-list'],
    gallery: ['gallery-simple-grid', 'gallery-before-after'],
    principles: ['clarity', 'trust', 'mobile_first', 'conversion_path'],
    ctas: ['Call', 'WhatsApp', 'Book'],
  },
  creative_agency: {
    id: 'creative_agency',
    label: 'Creative Agency',
    match: /agency|studio|design|branding|marketing|creative|media/i,
    directions: ['asymmetric', 'experimental-grid', 'brutalist', 'magazine', 'editorial', 'agency-creative'],
    heroes: ['hero-asymmetric', 'hero-bento', 'hero-typography-first', 'hero-editorial'],
    services: ['services-bento', 'services-editorial', 'services-numbered'],
    gallery: ['gallery-bento', 'gallery-editorial', 'gallery-masonry'],
    principles: ['originality', 'visual_variety', 'typography_as_hero'],
    ctas: ['Start a project', 'Contact'],
  },
  photography: {
    id: 'photography',
    label: 'Photography',
    match: /photograph|photo studio|cinematograph|videograph/i,
    directions: ['image-first', 'neo-minimal', 'editorial', 'magazine', 'immersive'],
    heroes: ['hero-full-bleed', 'hero-typography-first', 'hero-immersive-stage'],
    services: ['services-minimal-rows', 'services-editorial', 'services-list'],
    gallery: ['gallery-masonry', 'gallery-immersive', 'gallery-editorial'],
    principles: ['imagery_first', 'negative_space', 'originality'],
    ctas: ['Book', 'WhatsApp'],
  },
  jewelry_luxury: {
    id: 'jewelry_luxury',
    label: 'Jewelry & Luxury',
    match: /jewel|diamond|luxury|watch|goldsmith/i,
    directions: ['minimal-luxury', 'editorial', 'soft-luxury', 'magazine', 'desert-luxury'],
    heroes: ['hero-centered-void', 'hero-editorial', 'hero-full-bleed', 'hero-soft-split'],
    services: ['services-list-luxury', 'services-editorial', 'services-soft-cards'],
    gallery: ['gallery-editorial', 'gallery-featured', 'gallery-masonry'],
    principles: ['whitespace', 'hierarchy', 'imagery_first', 'trust'],
    ctas: ['Enquire', 'Visit', 'WhatsApp'],
  },
  bakery_artisan: {
    id: 'bakery_artisan',
    label: 'Bakery & Artisan',
    match: /bakery|handcraft|artisan|cafe|pastry|coffee/i,
    directions: ['warm-retail', 'organic', 'soft-luxury', 'editorial', 'bakery-warm'],
    heroes: ['hero-soft-split', 'hero-full-bleed', 'hero-centered-void'],
    services: ['services-soft-cards', 'services-menu-cards', 'services-grid-3'],
    gallery: ['gallery-masonry', 'gallery-food-grid'],
    principles: ['warmth', 'imagery_first', 'local_trust'],
    ctas: ['Order', 'WhatsApp', 'Visit'],
  },
  travel_tourism: {
    id: 'travel_tourism',
    label: 'Travel & Tourism',
    match: /travel|tour|holiday|destination|trek|visa/i,
    directions: ['immersive', 'image-first', 'organic', 'coastal', 'editorial'],
    heroes: ['hero-immersive-stage', 'hero-full-bleed', 'hero-card-overlay'],
    services: ['services-amenity-grid', 'services-grid-3', 'services-editorial'],
    gallery: ['gallery-immersive', 'gallery-masonry', 'gallery-featured'],
    principles: ['atmosphere', 'imagery_first', 'conversion_path'],
    ctas: ['Enquire', 'WhatsApp', 'Book'],
  },
  nonprofit: {
    id: 'nonprofit',
    label: 'Nonprofit',
    match: /nonprofit|ngo|charity|foundation|community|trust\b/i,
    directions: ['organic', 'neo-minimal', 'corporate', 'education-bright', 'editorial'],
    heroes: ['hero-trust-band', 'hero-split', 'hero-centered-void'],
    services: ['services-list', 'services-grid-3', 'services-icon-rail'],
    gallery: ['gallery-simple-grid', 'gallery-masonry'],
    principles: ['trust', 'clarity', 'accessibility', 'authenticity'],
    ctas: ['Donate', 'Volunteer', 'Contact'],
  },
  finance_legal: {
    id: 'finance_legal',
    label: 'Finance & Legal',
    match: /bank|finance|loan|insurance|legal|law firm|tax/i,
    directions: ['finance-legal', 'corporate', 'neo-minimal', 'minimal-luxury'],
    heroes: ['hero-trust-band', 'hero-centered-void', 'hero-split'],
    services: ['services-list', 'services-icon-rail', 'services-grid-3'],
    gallery: ['gallery-simple-grid'],
    principles: ['trust', 'clarity', 'accessibility', 'consistency'],
    ctas: ['Enquire', 'Call', 'Book'],
  },
  industrial_trade: {
    id: 'industrial_trade',
    label: 'Industrial & Trade',
    match: /manufactur|factory|industrial|wholesale|hardware|construction|steel/i,
    directions: ['industrial', 'brutalist', 'corporate', 'neo-minimal', 'asymmetric'],
    heroes: ['hero-industrial', 'hero-split', 'hero-typography-first'],
    services: ['services-grid-3', 'services-list', 'services-icon-rail'],
    gallery: ['gallery-simple-grid', 'gallery-before-after'],
    principles: ['clarity', 'bold_hierarchy', 'trust'],
    ctas: ['Enquire', 'Call'],
  },
  pet_care: {
    id: 'pet_care',
    label: 'Pet Care',
    match: /pet|vet|veterinary|groom|dog|cat|animal/i,
    directions: ['warm-retail', 'soft-luxury', 'organic', 'education-bright', 'neo-minimal'],
    heroes: ['hero-soft-split', 'hero-full-bleed', 'hero-centered-void'],
    services: ['services-soft-cards', 'services-grid-3', 'services-icon-rail'],
    gallery: ['gallery-masonry', 'gallery-simple-grid'],
    principles: ['warmth', 'trust', 'mobile_first'],
    ctas: ['Book', 'WhatsApp', 'Call'],
  },
  events_wedding: {
    id: 'events_wedding',
    label: 'Events & Wedding',
    match: /wedding|event|planner|decorator|banquet|celebration/i,
    directions: ['soft-luxury', 'editorial', 'minimal-luxury', 'magazine', 'immersive'],
    heroes: ['hero-full-bleed', 'hero-editorial', 'hero-soft-split', 'hero-immersive-stage'],
    services: ['services-editorial', 'services-soft-cards', 'services-list-luxury'],
    gallery: ['gallery-masonry', 'gallery-editorial', 'gallery-featured'],
    principles: ['atmosphere', 'imagery_first', 'hierarchy', 'warmth'],
    ctas: ['Enquire', 'WhatsApp', 'Book'],
  },
  general_local: {
    id: 'general_local',
    label: 'Local Business',
    match: /.*/,
    directions: [
      'neo-minimal',
      'corporate',
      'editorial',
      'warm-retail',
      'asymmetric',
      'soft-luxury',
      'experimental-grid',
      'image-first',
    ],
    heroes: ['hero-split', 'hero-centered-void', 'hero-full-bleed', 'hero-asymmetric', 'hero-bento'],
    services: ['services-grid-3', 'services-list', 'services-soft-cards', 'services-bento'],
    gallery: ['gallery-simple-grid', 'gallery-masonry', 'gallery-featured'],
    principles: ['clarity', 'hierarchy', 'mobile_first', 'conversion_path', 'originality'],
    ctas: ['WhatsApp', 'Call', 'Enquire'],
  },
})

export function resolveIndustry(category = '', subcategory = '', prompt = '') {
  const hay = `${category} ${subcategory} ${prompt}`
  for (const id of INDUSTRY_IDS) {
    if (id === 'general_local') continue
    if (INDUSTRIES[id].match.test(hay)) return INDUSTRIES[id]
  }
  return INDUSTRIES.general_local
}

export function industryDirectionPool(category, subcategory, prompt) {
  return [...resolveIndustry(category, subcategory, prompt).directions]
}

export { INDUSTRIES }
