/**
 * Expanded visual directions for the Design Explorer.
 * Keep ids stable — industries.js and learning refer to these keys.
 */

const BASE = {
  editorial: {
    id: 'editorial',
    label: 'Editorial',
    navigationStrategy: 'top-ruled',
    heroComposition: 'typographic-column',
    sectionOrder: ['hero', 'about', 'services', 'reviews', 'contact', 'footer'],
    gridStrategy: '12-column-editorial',
    typographyHierarchy: { heading: 'Playfair Display, Georgia, serif', body: 'Newsreader, Georgia, serif', scale: 'display' },
    colorStrategy: { background: '#f4efe6', surface: '#fffaf2', heading: '#1a1410', text: '#2c241c', accent: '#8a1f12', accentText: '#fffaf2', heroBg: '#1a1410', heroFg: '#f4efe6' },
    ctaPlacement: 'hero-inline-plus-end-band',
    cardStrategy: 'ruled-text-first',
    imageTreatment: 'print-crop',
    interactionStyle: 'slow-underline',
    footerStrategy: 'colophon',
    mobileStrategy: 'accordion-menu',
    layoutStyle: 'editorial-column',
    spacing: 'generous-vertical',
    buttons: 'underlined-text',
    animation: 'fade-up',
  },
  'image-first': {
    id: 'image-first',
    label: 'Image-first',
    navigationStrategy: 'overlay-on-media',
    heroComposition: 'full-bleed-photo',
    sectionOrder: ['hero', 'gallery', 'services', 'about', 'contact', 'footer'],
    gridStrategy: 'mosaic',
    typographyHierarchy: { heading: 'Inter, Helvetica, sans-serif', body: 'Inter, Helvetica, sans-serif', scale: 'quiet' },
    colorStrategy: { background: '#0c0c0c', surface: '#161616', heading: '#f7f7f7', text: '#d4d4d4', accent: '#ffffff', accentText: '#111111', heroBg: '#050505', heroFg: '#ffffff' },
    ctaPlacement: 'floating-over-image',
    cardStrategy: 'photo-tile',
    imageTreatment: 'full-bleed-edge',
    interactionStyle: 'parallax-lite',
    footerStrategy: 'dark-minimal',
    mobileStrategy: 'bottom-sheet-menu',
    layoutStyle: 'media-dominant',
    spacing: 'flush',
    buttons: 'ghost-on-photo',
    animation: 'ken-burns',
  },
  'minimal-luxury': {
    id: 'minimal-luxury',
    label: 'Minimal Luxury',
    navigationStrategy: 'hairline-top',
    heroComposition: 'centered-void',
    sectionOrder: ['hero', 'services', 'about', 'reviews', 'contact', 'footer'],
    gridStrategy: 'two-column-wide-margins',
    typographyHierarchy: { heading: 'Cormorant Garamond, Georgia, serif', body: 'Jost, Helvetica, sans-serif', scale: 'restrained' },
    colorStrategy: { background: '#fbfaf7', surface: '#ffffff', heading: '#111111', text: '#3a3a3a', accent: '#111111', accentText: '#fbfaf7', heroBg: '#fbfaf7', heroFg: '#111111' },
    ctaPlacement: 'single-centered',
    cardStrategy: 'borderless-quiet',
    imageTreatment: 'soft-rect',
    interactionStyle: 'still',
    footerStrategy: 'thin-centered',
    mobileStrategy: 'simple-collapse',
    layoutStyle: 'luxury-whitespace',
    spacing: 'vast',
    buttons: 'pill-outline',
    animation: 'none',
  },
  asymmetric: {
    id: 'asymmetric',
    label: 'Asymmetric',
    navigationStrategy: 'left-rail',
    heroComposition: 'offset-split',
    sectionOrder: ['hero', 'services', 'gallery', 'about', 'contact', 'footer'],
    gridStrategy: 'broken-columns',
    typographyHierarchy: { heading: 'Syne, Futura, sans-serif', body: 'Manrope, Helvetica, sans-serif', scale: 'uneven' },
    colorStrategy: { background: '#efe7ff', surface: '#ffffff', heading: '#16083a', text: '#2a1b4f', accent: '#5b2dff', accentText: '#ffffff', heroBg: '#16083a', heroFg: '#efe7ff' },
    ctaPlacement: 'staggered-pair',
    cardStrategy: 'shifted-stack',
    imageTreatment: 'angled-clip',
    interactionStyle: 'spring-shift',
    footerStrategy: 'split-asymmetric',
    mobileStrategy: 'rail-to-top',
    layoutStyle: 'asymmetric-blocks',
    spacing: 'irregular',
    buttons: 'hard-rect',
    animation: 'slide-askew',
  },
  magazine: {
    id: 'magazine',
    label: 'Magazine',
    navigationStrategy: 'issue-masthead',
    heroComposition: 'headline-deck-spread',
    sectionOrder: ['hero', 'reviews', 'about', 'services', 'gallery', 'contact', 'footer'],
    gridStrategy: 'magazine-modules',
    typographyHierarchy: { heading: 'Oswald, Impact, sans-serif', body: 'Source Serif 4, Georgia, serif', scale: 'cover-story' },
    colorStrategy: { background: '#ffffff', surface: '#f2f2f2', heading: '#111111', text: '#222222', accent: '#d62828', accentText: '#ffffff', heroBg: '#111111', heroFg: '#ffffff' },
    ctaPlacement: 'kicker-row',
    cardStrategy: 'article-deck',
    imageTreatment: 'captioned-plate',
    interactionStyle: 'page-flip',
    footerStrategy: 'index-columns',
    mobileStrategy: 'stacked-issue',
    layoutStyle: 'magazine-spread',
    spacing: 'tight-modules',
    buttons: 'box-label',
    animation: 'cut',
  },
  immersive: {
    id: 'immersive',
    label: 'Immersive',
    navigationStrategy: 'hidden-until-hover',
    heroComposition: 'viewport-stage',
    sectionOrder: ['hero', 'about', 'gallery', 'services', 'contact', 'footer'],
    gridStrategy: 'full-viewport-snaps',
    typographyHierarchy: { heading: 'Bebas Neue, Impact, sans-serif', body: 'Karla, Helvetica, sans-serif', scale: 'cinematic' },
    colorStrategy: { background: '#05070a', surface: '#10141c', heading: '#e8f4ff', text: '#c5d4e3', accent: '#3dd6c6', accentText: '#05070a', heroBg: '#020308', heroFg: '#e8f4ff' },
    ctaPlacement: 'stage-bottom',
    cardStrategy: 'scene-panels',
    imageTreatment: 'cinematic-grade',
    interactionStyle: 'scroll-hijack-lite',
    footerStrategy: 'end-credits',
    mobileStrategy: 'swipe-scenes',
    layoutStyle: 'immersive-stage',
    spacing: 'viewport',
    buttons: 'glow-pill',
    animation: 'cinematic-fade',
  },
  'experimental-grid': {
    id: 'experimental-grid',
    label: 'Experimental Grid',
    navigationStrategy: 'cell-nav',
    heroComposition: 'bento-hero',
    sectionOrder: ['hero', 'services', 'gallery', 'reviews', 'about', 'contact', 'footer'],
    gridStrategy: 'bento-12',
    typographyHierarchy: { heading: 'Space Grotesk, Helvetica, sans-serif', body: 'IBM Plex Sans, Helvetica, sans-serif', scale: 'modular' },
    colorStrategy: { background: '#f5f7fa', surface: '#ffffff', heading: '#0b1f33', text: '#24394d', accent: '#ff5a1f', accentText: '#ffffff', heroBg: '#0b1f33', heroFg: '#f5f7fa' },
    ctaPlacement: 'grid-cell',
    cardStrategy: 'bento-cells',
    imageTreatment: 'hard-crop-grid',
    interactionStyle: 'cell-hover',
    footerStrategy: 'grid-endcap',
    mobileStrategy: 'single-column-bento',
    layoutStyle: 'experimental-bento',
    spacing: 'gutter-tight',
    buttons: 'cell-fill',
    animation: 'stagger-cells',
  },
  'soft-luxury': {
    id: 'soft-luxury',
    label: 'Soft Luxury',
    navigationStrategy: 'pill-header',
    heroComposition: 'soft-split-portrait',
    sectionOrder: ['hero', 'about', 'reviews', 'services', 'contact', 'footer'],
    gridStrategy: 'rounded-cards',
    typographyHierarchy: { heading: 'Fraunces, Georgia, serif', body: 'Nunito Sans, Helvetica, sans-serif', scale: 'warm' },
    colorStrategy: { background: '#f8efe8', surface: '#fff8f3', heading: '#3d2b24', text: '#5a433a', accent: '#c4785a', accentText: '#fff8f3', heroBg: '#ead9cf', heroFg: '#3d2b24' },
    ctaPlacement: 'soft-pair',
    cardStrategy: 'rounded-shadow',
    imageTreatment: 'blush-radius',
    interactionStyle: 'gentle-lift',
    footerStrategy: 'warm-band',
    mobileStrategy: 'rounded-drawer',
    layoutStyle: 'soft-luxury',
    spacing: 'plush',
    buttons: 'rounded-fill',
    animation: 'soft-rise',
  },
  'neo-minimal': {
    id: 'neo-minimal',
    label: 'Neo-Minimal',
    navigationStrategy: 'tiny-wordmark',
    heroComposition: 'one-line-hero',
    sectionOrder: ['hero', 'services', 'contact', 'about', 'footer'],
    gridStrategy: 'single-track',
    typographyHierarchy: { heading: 'Helvetica Neue, Helvetica, sans-serif', body: 'Helvetica Neue, Helvetica, sans-serif', scale: 'micro' },
    colorStrategy: { background: '#ffffff', surface: '#ffffff', heading: '#000000', text: '#111111', accent: '#000000', accentText: '#ffffff', heroBg: '#ffffff', heroFg: '#000000' },
    ctaPlacement: 'text-link',
    cardStrategy: 'list-rows',
    imageTreatment: 'none-or-line',
    interactionStyle: 'instant',
    footerStrategy: 'one-line',
    mobileStrategy: 'unstyled-details',
    layoutStyle: 'neo-minimal',
    spacing: 'system',
    buttons: 'text-only',
    animation: 'none',
  },
}

const EXTRA = {
  brutalist: {
    id: 'brutalist',
    label: 'Brutalist',
    navigationStrategy: 'raw-links',
    heroComposition: 'hard-type-block',
    sectionOrder: ['hero', 'services', 'about', 'gallery', 'contact', 'footer'],
    gridStrategy: 'rigid-columns',
    typographyHierarchy: { heading: 'Arial Black, Impact, sans-serif', body: 'Courier New, monospace', scale: 'shout' },
    colorStrategy: { background: '#f2f2f2', surface: '#ffffff', heading: '#000000', text: '#111111', accent: '#ff0000', accentText: '#ffffff', heroBg: '#000000', heroFg: '#ffff00' },
    ctaPlacement: 'hard-stack',
    cardStrategy: 'border-thick',
    imageTreatment: 'raw-unmasked',
    interactionStyle: 'instant-hard',
    footerStrategy: 'mono-strip',
    mobileStrategy: 'stack-hard',
    layoutStyle: 'brutalist',
    spacing: 'dense',
    buttons: 'square-fill',
    animation: 'none',
  },
  corporate: {
    id: 'corporate',
    label: 'Corporate',
    navigationStrategy: 'utility-top',
    heroComposition: 'trust-split',
    sectionOrder: ['hero', 'services', 'about', 'reviews', 'contact', 'footer'],
    gridStrategy: '12-business',
    typographyHierarchy: { heading: 'Source Sans 3, Helvetica, sans-serif', body: 'Source Sans 3, Helvetica, sans-serif', scale: 'business' },
    colorStrategy: { background: '#f7f9fc', surface: '#ffffff', heading: '#0f2744', text: '#334155', accent: '#1d4ed8', accentText: '#ffffff', heroBg: '#0f2744', heroFg: '#f7f9fc' },
    ctaPlacement: 'primary-secondary',
    cardStrategy: 'elevated-quiet',
    imageTreatment: 'clean-rect',
    interactionStyle: 'subtle-fade',
    footerStrategy: 'corporate-columns',
    mobileStrategy: 'simple-collapse',
    layoutStyle: 'corporate',
    spacing: 'even',
    buttons: 'rounded-rect',
    animation: 'fade',
  },
  organic: {
    id: 'organic',
    label: 'Organic',
    navigationStrategy: 'soft-top',
    heroComposition: 'nature-split',
    sectionOrder: ['hero', 'about', 'gallery', 'services', 'contact', 'footer'],
    gridStrategy: 'flowing',
    typographyHierarchy: { heading: 'Literata, Georgia, serif', body: 'Source Sans 3, Helvetica, sans-serif', scale: 'natural' },
    colorStrategy: { background: '#f3f6f0', surface: '#ffffff', heading: '#1f3324', text: '#3d5245', accent: '#3f6b4a', accentText: '#ffffff', heroBg: '#dfe8d8', heroFg: '#1f3324' },
    ctaPlacement: 'soft-pair',
    cardStrategy: 'leaf-radius',
    imageTreatment: 'natural-crop',
    interactionStyle: 'gentle-lift',
    footerStrategy: 'earth-band',
    mobileStrategy: 'simple-collapse',
    layoutStyle: 'organic',
    spacing: 'breathing',
    buttons: 'pill-fill',
    animation: 'soft-rise',
  },
  coastal: {
    id: 'coastal',
    label: 'Coastal',
    navigationStrategy: 'air-top',
    heroComposition: 'horizon-bleed',
    sectionOrder: ['hero', 'gallery', 'about', 'services', 'contact', 'footer'],
    gridStrategy: 'wide-horizon',
    typographyHierarchy: { heading: 'DM Serif Display, Georgia, serif', body: 'DM Sans, Helvetica, sans-serif', scale: 'airy' },
    colorStrategy: { background: '#f2f7fb', surface: '#ffffff', heading: '#123047', text: '#355066', accent: '#2a7f9e', accentText: '#ffffff', heroBg: '#0d3b52', heroFg: '#f2f7fb' },
    ctaPlacement: 'horizon-cta',
    cardStrategy: 'soft-sea',
    imageTreatment: 'wide-crop',
    interactionStyle: 'slow-fade',
    footerStrategy: 'tide-band',
    mobileStrategy: 'simple-collapse',
    layoutStyle: 'coastal',
    spacing: 'open',
    buttons: 'pill-outline',
    animation: 'fade-up',
  },
  'wellness-zen': {
    id: 'wellness-zen',
    label: 'Wellness Zen',
    navigationStrategy: 'quiet-top',
    heroComposition: 'meditative-center',
    sectionOrder: ['hero', 'about', 'services', 'reviews', 'contact', 'footer'],
    gridStrategy: 'calm-columns',
    typographyHierarchy: { heading: 'Cormorant, Georgia, serif', body: 'Work Sans, Helvetica, sans-serif', scale: 'calm' },
    colorStrategy: { background: '#f7f4ef', surface: '#fffcf8', heading: '#2c2a26', text: '#5a564e', accent: '#6b7f5c', accentText: '#fffcf8', heroBg: '#ebe4da', heroFg: '#2c2a26' },
    ctaPlacement: 'single-centered',
    cardStrategy: 'quiet-tiles',
    imageTreatment: 'soft-rect',
    interactionStyle: 'still',
    footerStrategy: 'thin-centered',
    mobileStrategy: 'simple-collapse',
    layoutStyle: 'wellness-zen',
    spacing: 'vast',
    buttons: 'pill-outline',
    animation: 'none',
  },
  'warm-retail': {
    id: 'warm-retail',
    label: 'Warm Retail',
    navigationStrategy: 'shop-top',
    heroComposition: 'shop-window',
    sectionOrder: ['hero', 'offers', 'products', 'about', 'contact', 'footer'],
    gridStrategy: 'retail-shelves',
    typographyHierarchy: { heading: 'Fraunces, Georgia, serif', body: 'Karla, Helvetica, sans-serif', scale: 'friendly' },
    colorStrategy: { background: '#fff8f1', surface: '#ffffff', heading: '#3b2417', text: '#5c4033', accent: '#c45c26', accentText: '#fff8f1', heroBg: '#3b2417', heroFg: '#fff8f1' },
    ctaPlacement: 'shop-pair',
    cardStrategy: 'product-tile',
    imageTreatment: 'warm-crop',
    interactionStyle: 'gentle-lift',
    footerStrategy: 'warm-band',
    mobileStrategy: 'bottom-sheet-menu',
    layoutStyle: 'warm-retail',
    spacing: 'plush',
    buttons: 'rounded-fill',
    animation: 'soft-rise',
  },
  'tech-dark': {
    id: 'tech-dark',
    label: 'Tech Dark',
    navigationStrategy: 'glass-top',
    heroComposition: 'product-glow',
    sectionOrder: ['hero', 'services', 'about', 'contact', 'footer'],
    gridStrategy: 'product-12',
    typographyHierarchy: { heading: 'Space Grotesk, Helvetica, sans-serif', body: 'Inter, Helvetica, sans-serif', scale: 'product' },
    colorStrategy: { background: '#0b1020', surface: '#141a2e', heading: '#e8eefc', text: '#a8b3cf', accent: '#5b8cff', accentText: '#0b1020', heroBg: '#070b16', heroFg: '#e8eefc' },
    ctaPlacement: 'primary-secondary',
    cardStrategy: 'glass-tile',
    imageTreatment: 'ui-frame',
    interactionStyle: 'soft-glow',
    footerStrategy: 'dark-minimal',
    mobileStrategy: 'simple-collapse',
    layoutStyle: 'tech-dark',
    spacing: 'even',
    buttons: 'glow-pill',
    animation: 'fade-up',
  },
  'saas-product': {
    id: 'saas-product',
    label: 'SaaS Product',
    navigationStrategy: 'product-top',
    heroComposition: 'app-shot-split',
    sectionOrder: ['hero', 'services', 'reviews', 'about', 'contact', 'footer'],
    gridStrategy: 'feature-grid',
    typographyHierarchy: { heading: 'Inter, Helvetica, sans-serif', body: 'Inter, Helvetica, sans-serif', scale: 'ui' },
    colorStrategy: { background: '#f8fafc', surface: '#ffffff', heading: '#0f172a', text: '#475569', accent: '#4f46e5', accentText: '#ffffff', heroBg: '#0f172a', heroFg: '#f8fafc' },
    ctaPlacement: 'primary-secondary',
    cardStrategy: 'feature-card',
    imageTreatment: 'ui-frame',
    interactionStyle: 'subtle-fade',
    footerStrategy: 'corporate-columns',
    mobileStrategy: 'simple-collapse',
    layoutStyle: 'saas-product',
    spacing: 'system',
    buttons: 'rounded-rect',
    animation: 'fade',
  },
  'clinical-clean': {
    id: 'clinical-clean',
    label: 'Clinical Clean',
    navigationStrategy: 'utility-top',
    heroComposition: 'clinic-split',
    sectionOrder: ['hero', 'services', 'about', 'hours', 'contact', 'footer'],
    gridStrategy: 'clean-12',
    typographyHierarchy: { heading: 'IBM Plex Sans, Helvetica, sans-serif', body: 'IBM Plex Sans, Helvetica, sans-serif', scale: 'clinical' },
    colorStrategy: { background: '#f5f9fb', surface: '#ffffff', heading: '#0b3a4a', text: '#355a66', accent: '#0d8a7f', accentText: '#ffffff', heroBg: '#e8f3f6', heroFg: '#0b3a4a' },
    ctaPlacement: 'primary-secondary',
    cardStrategy: 'clean-list',
    imageTreatment: 'clean-rect',
    interactionStyle: 'subtle-fade',
    footerStrategy: 'corporate-columns',
    mobileStrategy: 'simple-collapse',
    layoutStyle: 'clinical-clean',
    spacing: 'even',
    buttons: 'rounded-rect',
    animation: 'fade',
  },
  'fitness-energy': {
    id: 'fitness-energy',
    label: 'Fitness Energy',
    navigationStrategy: 'bold-top',
    heroComposition: 'action-bleed',
    sectionOrder: ['hero', 'services', 'gallery', 'reviews', 'contact', 'footer'],
    gridStrategy: 'power-grid',
    typographyHierarchy: { heading: 'Oswald, Impact, sans-serif', body: 'Barlow, Helvetica, sans-serif', scale: 'power' },
    colorStrategy: { background: '#0f0f0f', surface: '#1a1a1a', heading: '#ffffff', text: '#d4d4d4', accent: '#ef4444', accentText: '#ffffff', heroBg: '#000000', heroFg: '#ffffff' },
    ctaPlacement: 'hard-stack',
    cardStrategy: 'power-tiles',
    imageTreatment: 'action-crop',
    interactionStyle: 'spring-shift',
    footerStrategy: 'dark-minimal',
    mobileStrategy: 'stack-hard',
    layoutStyle: 'fitness-energy',
    spacing: 'dense',
    buttons: 'square-fill',
    animation: 'slide-askew',
  },
  'real-estate-airy': {
    id: 'real-estate-airy',
    label: 'Real Estate Airy',
    navigationStrategy: 'listing-top',
    heroComposition: 'property-bleed',
    sectionOrder: ['hero', 'gallery', 'services', 'about', 'contact', 'footer'],
    gridStrategy: 'listing-12',
    typographyHierarchy: { heading: 'Libre Franklin, Helvetica, sans-serif', body: 'Libre Franklin, Helvetica, sans-serif', scale: 'listing' },
    colorStrategy: { background: '#f7f7f5', surface: '#ffffff', heading: '#1c1917', text: '#44403c', accent: '#0f766e', accentText: '#ffffff', heroBg: '#1c1917', heroFg: '#f7f7f5' },
    ctaPlacement: 'primary-secondary',
    cardStrategy: 'listing-card',
    imageTreatment: 'wide-crop',
    interactionStyle: 'subtle-fade',
    footerStrategy: 'corporate-columns',
    mobileStrategy: 'simple-collapse',
    layoutStyle: 'real-estate-airy',
    spacing: 'open',
    buttons: 'rounded-rect',
    animation: 'fade-up',
  },
  'education-bright': {
    id: 'education-bright',
    label: 'Education Bright',
    navigationStrategy: 'campus-top',
    heroComposition: 'campus-split',
    sectionOrder: ['hero', 'services', 'about', 'reviews', 'contact', 'footer'],
    gridStrategy: 'campus-12',
    typographyHierarchy: { heading: 'Nunito, Helvetica, sans-serif', body: 'Nunito, Helvetica, sans-serif', scale: 'friendly' },
    colorStrategy: { background: '#f8fafc', surface: '#ffffff', heading: '#1e3a5f', text: '#475569', accent: '#2563eb', accentText: '#ffffff', heroBg: '#dbeafe', heroFg: '#1e3a5f' },
    ctaPlacement: 'primary-secondary',
    cardStrategy: 'course-card',
    imageTreatment: 'clean-rect',
    interactionStyle: 'gentle-lift',
    footerStrategy: 'corporate-columns',
    mobileStrategy: 'simple-collapse',
    layoutStyle: 'education-bright',
    spacing: 'even',
    buttons: 'rounded-fill',
    animation: 'soft-rise',
  },
  'finance-legal': {
    id: 'finance-legal',
    label: 'Finance & Legal',
    navigationStrategy: 'formal-top',
    heroComposition: 'formal-split',
    sectionOrder: ['hero', 'services', 'about', 'contact', 'footer'],
    gridStrategy: 'formal-12',
    typographyHierarchy: { heading: 'Libre Baskerville, Georgia, serif', body: 'Source Sans 3, Helvetica, sans-serif', scale: 'formal' },
    colorStrategy: { background: '#f6f7f9', surface: '#ffffff', heading: '#111827', text: '#374151', accent: '#1e3a5f', accentText: '#ffffff', heroBg: '#111827', heroFg: '#f6f7f9' },
    ctaPlacement: 'primary-secondary',
    cardStrategy: 'formal-card',
    imageTreatment: 'clean-rect',
    interactionStyle: 'still',
    footerStrategy: 'corporate-columns',
    mobileStrategy: 'simple-collapse',
    layoutStyle: 'finance-legal',
    spacing: 'even',
    buttons: 'rounded-rect',
    animation: 'none',
  },
  industrial: {
    id: 'industrial',
    label: 'Industrial',
    navigationStrategy: 'steel-top',
    heroComposition: 'workshop-bleed',
    sectionOrder: ['hero', 'services', 'gallery', 'about', 'contact', 'footer'],
    gridStrategy: 'steel-grid',
    typographyHierarchy: { heading: 'Barlow Condensed, Impact, sans-serif', body: 'Barlow, Helvetica, sans-serif', scale: 'industrial' },
    colorStrategy: { background: '#eceff1', surface: '#ffffff', heading: '#263238', text: '#455a64', accent: '#ff6f00', accentText: '#ffffff', heroBg: '#263238', heroFg: '#eceff1' },
    ctaPlacement: 'hard-stack',
    cardStrategy: 'steel-tile',
    imageTreatment: 'raw-unmasked',
    interactionStyle: 'instant-hard',
    footerStrategy: 'mono-strip',
    mobileStrategy: 'stack-hard',
    layoutStyle: 'industrial',
    spacing: 'dense',
    buttons: 'square-fill',
    animation: 'cut',
  },
  'agency-creative': {
    id: 'agency-creative',
    label: 'Agency Creative',
    navigationStrategy: 'studio-top',
    heroComposition: 'studio-asymmetric',
    sectionOrder: ['hero', 'gallery', 'services', 'about', 'contact', 'footer'],
    gridStrategy: 'studio-broken',
    typographyHierarchy: { heading: 'Syne, Futura, sans-serif', body: 'Manrope, Helvetica, sans-serif', scale: 'studio' },
    colorStrategy: { background: '#fafafa', surface: '#ffffff', heading: '#111111', text: '#333333', accent: '#111111', accentText: '#ffffff', heroBg: '#111111', heroFg: '#fafafa' },
    ctaPlacement: 'staggered-pair',
    cardStrategy: 'studio-frame',
    imageTreatment: 'hard-crop-grid',
    interactionStyle: 'spring-shift',
    footerStrategy: 'colophon',
    mobileStrategy: 'rail-to-top',
    layoutStyle: 'agency-creative',
    spacing: 'irregular',
    buttons: 'hard-rect',
    animation: 'stagger-cells',
  },
  'bakery-warm': {
    id: 'bakery-warm',
    label: 'Bakery Warm',
    navigationStrategy: 'shop-top',
    heroComposition: 'bakery-window',
    sectionOrder: ['hero', 'offers', 'gallery', 'about', 'contact', 'footer'],
    gridStrategy: 'bakery-shelves',
    typographyHierarchy: { heading: 'Fraunces, Georgia, serif', body: 'Nunito Sans, Helvetica, sans-serif', scale: 'warm' },
    colorStrategy: { background: '#fff7ed', surface: '#ffffff', heading: '#7c2d12', text: '#9a3412', accent: '#ea580c', accentText: '#fff7ed', heroBg: '#fed7aa', heroFg: '#7c2d12' },
    ctaPlacement: 'soft-pair',
    cardStrategy: 'pastry-tile',
    imageTreatment: 'warm-crop',
    interactionStyle: 'gentle-lift',
    footerStrategy: 'warm-band',
    mobileStrategy: 'rounded-drawer',
    layoutStyle: 'bakery-warm',
    spacing: 'plush',
    buttons: 'rounded-fill',
    animation: 'soft-rise',
  },
  'desert-luxury': {
    id: 'desert-luxury',
    label: 'Desert Luxury',
    navigationStrategy: 'hairline-top',
    heroComposition: 'sand-void',
    sectionOrder: ['hero', 'gallery', 'services', 'about', 'contact', 'footer'],
    gridStrategy: 'two-column-wide-margins',
    typographyHierarchy: { heading: 'Cormorant Garamond, Georgia, serif', body: 'Jost, Helvetica, sans-serif', scale: 'restrained' },
    colorStrategy: { background: '#f7f1e8', surface: '#fffdf8', heading: '#3b2f2f', text: '#5c4e4e', accent: '#a67c52', accentText: '#fffdf8', heroBg: '#e8dcc8', heroFg: '#3b2f2f' },
    ctaPlacement: 'single-centered',
    cardStrategy: 'borderless-quiet',
    imageTreatment: 'soft-rect',
    interactionStyle: 'still',
    footerStrategy: 'thin-centered',
    mobileStrategy: 'simple-collapse',
    layoutStyle: 'desert-luxury',
    spacing: 'vast',
    buttons: 'pill-outline',
    animation: 'none',
  },
}

export const DIRECTIONS = Object.freeze({ ...BASE, ...EXTRA })
export const DIRECTION_IDS = Object.freeze(Object.keys(DIRECTIONS))

export function specFromDirection(id) {
  const row = DIRECTIONS[id] || DIRECTIONS.editorial
  return {
    direction: row.id,
    label: row.label,
    navigationStrategy: row.navigationStrategy,
    heroComposition: row.heroComposition,
    sectionOrder: [...row.sectionOrder],
    gridStrategy: row.gridStrategy,
    typographyHierarchy: { ...row.typographyHierarchy },
    colorStrategy: { ...row.colorStrategy },
    ctaPlacement: row.ctaPlacement,
    cardStrategy: row.cardStrategy,
    imageTreatment: row.imageTreatment,
    interactionStyle: row.interactionStyle,
    footerStrategy: row.footerStrategy,
    mobileStrategy: row.mobileStrategy,
    layoutStyle: row.layoutStyle,
    spacing: row.spacing,
    buttons: row.buttons,
    animation: row.animation,
  }
}

export function dnaFromSpec(spec, { novelty = 3 } = {}) {
  return {
    direction: spec.direction,
    layoutStyle: spec.layoutStyle,
    navigationStyle: spec.navigationStrategy,
    heroStyle: spec.heroComposition,
    typography: spec.typographyHierarchy,
    colors: spec.colorStrategy,
    colorSystem: spec.colorStrategy,
    cards: spec.cardStrategy,
    cardStyle: spec.cardStrategy,
    buttons: spec.buttons,
    buttonStyle: spec.buttons,
    spacing: spec.spacing,
    sectionRhythm: spec.spacing,
    imageTreatment: spec.imageTreatment,
    interactions: spec.interactionStyle,
    interactionStyle: spec.interactionStyle,
    footer: spec.footerStrategy,
    footerStyle: spec.footerStrategy,
    animation: spec.animation,
    animationStyle: spec.animation,
    novelty,
  }
}

export function compositionKey(specOrDna) {
  const row = specOrDna || {}
  return [
    row.direction || row.layoutStyle,
    row.navigationStrategy || row.navigationStyle,
    row.heroComposition || row.heroStyle,
    row.gridStrategy,
    row.ctaPlacement,
    row.cardStrategy || row.cards,
    row.footerStrategy || row.footer,
  ]
    .filter(Boolean)
    .join('|')
}
